---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: HomeLab @ Homepage

background: 
  image: https://images.unsplash.com/photo-1563863251222-11d3e3bd3b62?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

layout:
  Networking:
    icon: mdi-network-#FFFFFF
  Infrastructure and Data:
    icon: mdi-server-#FFFFFF
  Management:
    icon: mdi-auto-fix-#FFFFFF
  Monitoring:
    icon: mdi-list-status-#FFFFFF
  Automation:
    icon: mdi-cog-play-#FFFFFF
  IoT and Smarthome:
    icon: mdi-home-#FFFFFF
  Security and Identity:
    icon: mdi-shield-lock-#FFFFFF
